apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-qa
  namespace: qa
  labels:
    app: kafka-ui-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-qa
  template:
    metadata:
      labels:
        app: kafka-ui-qa
    spec:
      containers:
      - name: kafka-ui-qa
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "crs-kafka-qa"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "kafka-cluster.qa.svc.cluster.local:9092"
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          value: "crs-zookeeper.qa.svc.cluster.local:2181"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-qa
  namespace: qa
spec:
  type: NodePort
  selector:
    app: kafka-ui-qa
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30081
